<?php
/**
 * @file
 * Custom code.
 */

function journalcxn_customizations_form_comment_node_deaccession_form_alter(&$form, &$form_state, $form_id) {
  // Disable the homepage field on the comment form.
  $form['author']['homepage']['#access'] = FALSE;
  // Change submit button text.
  $form['actions']['submit']['#value'] = 'Submit';
  // Display a message about titles split across locations.
  if ($form['#node']->field_dxn_split[LANGUAGE_NONE][0]['value'] == '1') {
    $form['split'] = array(
      '#markup' => '<p class="alert-box info">This title has holdings in both the Annex and another Library location, so the Library will consider faculty feedback in making a final decision regarding the disposition of this material.</p>',
      '#weight' => -10,
    );
  }
}
